/**
 * 一屏一层（批12）：点首页那两块换的是整屏页面，不是盖在首页上的一张半透卡；
 * 三处出口念同一份「返回」。`app.ts` 经 `rules.json?raw` 进不了 node 测试，
 * 所以那几条文本质疑挂在 `test:style` 上，能真跑的两句（BACK／entryHead/page 的类名）挂在 `test:ui` 上。
 * 2026-09-29 每把跑过 `npm run knives -- one-page --verbose`，`expect` 从实际红字逐字抄回。
 * 跑法：npm run knives -- one-page（全跑就 npm run knives；看每刀全红几句加 --verbose）
 */
export default {
  id: 'one-page',
  title: '点入口换页面不叠卡：整屏那层不透明、撑满一屏，三处出口同一份「返回」（批12）',
  via: 'test',
  suite: 'test:style',
  knives: [
    {
      rel: 'src/web/app.ts',
      note: 'A 那颗又按「身后有没有牌桌」分两种名字（那一屏整屏盖着牌桌，掀开看见的其实是首页）',
      from: '      leave.textContent = BACK;',
      to: "      leave.textContent = this.shell ? '看牌桌' : BACK;",
      expect: '那颗不再按「身后有没有牌桌」分两种名字',
    },
    {
      rel: 'src/web/app.ts',
      note: 'B 单机那一屏的标题自己写死一份（首页那块的字跟着改就漂成两个名字）',
      from: "    const { veil, body, foot } = page(this.root, entryHead('solo'));",
      to: "    const { veil, body, foot } = page(this.root, '单机模式');",
      expect: '两屏的标题就是首页那两块的字',
    },
    {
      rel: 'src/web/app.ts',
      note: 'C 那颗主按钮还留着弹窗那时代的名字（说明这一屏其实还是那张卡）',
      from: "        '开桌',\n        () => {\n          veil.remove();",
      to: "        '摆一桌',\n        () => {\n          veil.remove();",
      expect: '「摆一桌」那张弹窗卡没了（单机那一屏走整屏）',
    },
    {
      rel: 'src/web/style.css',
      note: 'D 整屏那层改成半透黑底（身后其实还挂着首页，半透就是把「还有一层」说出来）',
      from: '.sheet.as-page {\n  padding: 0;\n  place-items: stretch;\n  background: radial-gradient(120% 90% at 50% 0%, #35291f, var(--bg) 70%);',
      to: '.sheet.as-page {\n  padding: 0;\n  place-items: stretch;\n  background: rgba(20, 16, 12, 0.6);',
      expect: '整屏页那层不透明（跟首页同一份渐变，不是 rgba）',
    },
    {
      rel: 'src/web/style.css',
      note: 'E 卡还是被那道 88dvh 的顶掐着（整屏页滚到底也撑不满，底栏悬在半屏）',
      from: '.sheet.as-page .sheet-card {\n  width: min(var(--card-w), 100%);\n  max-height: none;',
      to: '.sheet.as-page .sheet-card {\n  width: min(var(--card-w), 100%);\n  max-height: 88dvh;',
      expect: '整屏页撑满一屏：那道 88dvh 的顶不再掐着它',
    },
    {
      rel: 'src/web/style.css',
      note: 'F 宽屏那一档没跟着放宽（大屏上整屏页瘦成窄窄一条）',
      from: '  .sheet.as-page .sheet-card {\n    width: min(var(--card-w-wide), 100%);\n  }',
      to: '  .sheet.as-page .sheet-card {\n    width: min(var(--card-w), 100%);\n  }',
      expect: '整屏页跟着宽屏那一档放宽',
    },
    {
      rel: 'src/web/home.ts',
      suite: 'test:ui',
      note: 'G 「返回」写回「回首页」：一条链上三颗出口各叫各的，人不知道哪颗把他从桌上摘下来',
      from: "export const BACK = '返回';",
      to: "export const BACK = '回首页';",
      expect: '每一屏那颗出口都念同一个词（不再「回首页」「退出这桌」各叫各的）',
    },
    {
      rel: 'src/web/home.ts',
      suite: 'test:ui',
      note: 'H 首页那两块的字改掉一份（点进去那一屏顶上还念旧名）',
      from: "  solo: { head: '单机模式',",
      to: "  solo: { head: '自己玩',",
      expect: '两块的字就是那两屏的标题，同一份来源',
    },
    {
      rel: 'src/web/ui.ts',
      suite: 'test:ui',
      note: 'I as-page 挂到卡上而不是遮罩上（底色、内边距都归遮罩，挂错了等于没整屏）',
      from: "  const c = card(root, title, cls);\n  c.veil.classList.add('as-page');",
      to: "  const c = card(root, title, cls);\n  c.body.classList.add('as-page');",
      expect: '.as-page 挂在遮罩上，不挂在卡上',
    },
    {
      rel: 'src/web/ui.ts',
      suite: 'test:ui',
      note: 'J 整屏那一页也挂上「点空白关掉」（宽屏上卡片两侧就是空白，点那儿等于凭空回了首页）',
      from: "  const c = card(root, title, cls);\n  c.veil.classList.add('as-page');",
      to: "  const c = card(root, title, cls);\n  c.veil.classList.add('as-page', 'tap-close');",
      expect: '整屏那一页不给「点空白关掉」：点遮罩它自己还挂着',
    },
    {
      rel: 'src/web/ui.ts',
      suite: 'test:ui',
      note: 'K 弹窗卡那条「点空白就关」的类没了（小手不给了，那句也读成哪儿都能点）',
      from: "    c.veil.classList.add('tap-close');",
      to: '',
      expect: '弹窗卡（不锁）挂的是 .tap-close',
    },
    {
      rel: 'src/web/ui.ts',
      suite: 'test:ui',
      note: 'L 类还挂着、监听拆了：看着能点空白，点了什么都不会发生（上面那句「页面点不掉」也就成了空跑出来的绿）',
      from: "    c.veil.addEventListener('click', (ev) => (ev.target === c.veil ? c.close() : undefined));",
      to: '',
      expect: '点一下空白那张弹窗卡就摘掉（不锁才算关得上，锁住的那种见 app 那几处 lock）',
    },
    {
      rel: 'src/web/style.css',
      note: 'M 往基础遮罩那层添一条模糊：页面自己也跟着糊一层（`.as-page` 压根不知道多了这条）',
      from: '.sheet {\n  position: fixed;\n  inset: 0;',
      to: '.sheet {\n  backdrop-filter: blur(3px);\n  position: fixed;\n  inset: 0;',
      expect: '遮罩那层照旧生效的只有「铺满一屏」那四件（没有半透底、没有内边距）',
    },
    {
      rel: 'src/web/style.css',
      note: 'N 往基础卡上描一条边：整屏那一页左右各露出一道卡边（那一屏本来就铺满，边是噪音）',
      from: '.sheet-card {\n  width: min(var(--card-w), 94vw);',
      to: '.sheet-card {\n  outline: 1px solid #5a4c3c;\n  width: min(var(--card-w), 94vw);',
      expect: '卡那层照旧生效的只有排版三件（边框、圆角、底色、投影都压掉了）',
    },
    {
      rel: 'src/web/style.css',
      note: 'O 提示条的层号掉到卡下面：那一句话被整屏页盖得一个字不剩',
      from: '  pointer-events: none;\n  z-index: 2100;',
      to: '  pointer-events: none;\n  z-index: 1500;',
      expect: '卡／整屏页之上只剩提示条那层，首页压在复盘之上（.drawer＜.home＜.sheet＜.toast）',
    },
    {
      rel: 'src/web/style.css',
      note: 'P 复盘那一格的层号高过卡：掀不开这一屏，还挡在钉住的那排按钮上',
      from: '.drawer {\n  position: fixed;\n  inset: auto 0 0 0;\n  z-index: 1900;',
      to: '.drawer {\n  position: fixed;\n  inset: auto 0 0 0;\n  z-index: 2500;',
      expect: '卡／整屏页之上只剩提示条那层，首页压在复盘之上（.drawer＜.home＜.sheet＜.toast）',
    },
    {
      rel: 'src/web/app.ts',
      note: 'Q 候场厅那一屏退回裸 card()：半透黑底＋居中卡又叠回首页上面（批12 摘掉的就是它）',
      from: "const { veil, head, body, foot } = page(this.root, '正连着这桌……', 'room');",
      to: "const { veil, head, body, foot } = card(this.root, '正连着这桌……', 'room');",
      expect: '牌桌外那一层的三屏全走 page()，一处也没退回裸 card()',
    },
    {
      rel: 'src/web/style.css',
      note: 'R 首页那层的层号退回跟复盘打平（1950 → 1900）：谁压谁又交回 DOM 顺序，改顺序就悄悄盖不住那一格',
      from: '.home {\n  position: fixed;\n  inset: 0;\n  z-index: 1950;',
      to: '.home {\n  position: fixed;\n  inset: 0;\n  z-index: 1900;',
      expect: '卡／整屏页之上只剩提示条那层，首页压在复盘之上（.drawer＜.home＜.sheet＜.toast）',
    },
    {
      rel: 'src/web/style.css',
      note: 'S 首页的层号高过卡跟提示条（1950 → 2500）：整屏那一页和那一句话都被首页盖死',
      from: '.home {\n  position: fixed;\n  inset: 0;\n  z-index: 1950;',
      to: '.home {\n  position: fixed;\n  inset: 0;\n  z-index: 2500;',
      expect: '首页压在牌桌之上、任何卡之下',
    },
  ],
};
